[package]
name = "spliterma"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.10"
vte4 = "0.9"
glib = "0.21"
gio = "0.21"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.99"
